### ISSUE TITLE
ReverseShell_2022_03.ps1 is splitting input at 35 characters

### ISSUE THREAD

**Issue by jdgregson** [tihanyin/PSSW100AVB#4]
The `ReverseShell_2022_03.ps1` script is splitting all commands at 35 characters for me, which breaks the command and makes it nearly impossible to do anything.

**Comment by tihanyin** [comment]
Hi Jonathan, 

Thanks for your feedback. You are right, but this limitation is intentionally. Line number 6, 7, 8 and 9 using a lot of characters when writing out the "Copyright (C) 2022 Microsoft Corporation. All rights reserved" string.
If you want to use very long commands for example like
 `mkdir VERY_long_directory_dd3ba2cca7da8526615be73d390527ac2`
then you have to add a new buffer after line 9. 

`[byte[]]$OO = 0..((2-shl(3*5))-1)|%{0};`
<img width="1340" alt="Screen Shot 2022-03-24 at 10 16 33 AM" src="https://user-images.githubusercontent.com/62064939/159854301-56407621-ff01-4044-809a-e3d7d76a285e.png">

`

I hope this answer your question.

Regards,
Norbert
